### ISSUE TITLE
Crash when opening camera

### ISSUE THREAD

**Issue by hansWURSCHT10000** [scoute-dich/PDFCreator#37]
Device: OnePlus 3
Android: 8.1.0 (OmniRom)

Logcat:
`
06-08 14:45:20.592  9106  9106 I ImagePicker: Adding intents of type: android.intent.action.PICK
06-08 14:45:20.598  9106  9106 I ImagePicker: App package: com.android.gallery3d
06-08 14:45:20.600  9106  9106 I ImagePicker: Adding intents of type: android.media.action.IMAGE_CAPTURE
06-08 14:45:20.601  9106  9106 I ImagePicker: App package: com.android.camera2
06-08 14:45:20.603  9106  9106 D AndroidRuntime: Shutting down VM
06-08 14:45:20.603  9106  9106 E AndroidRuntime: FATAL EXCEPTION: main
06-08 14:45:20.603  9106  9106 E AndroidRuntime: Process: de.baumann.pdfcreator, PID: 9106
06-08 14:45:20.603  9106  9106 E AndroidRuntime: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/de.baumann.pdfcreator/cache/tempImage exposed beyond app through ClipData.Item.getUri()
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.net.Uri.checkFileUriExposed(Uri.java:2356)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:942)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.content.Intent.prepareToLeaveProcess(Intent.java:9850)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.content.Intent.prepareToLeaveProcess(Intent.java:9856)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.content.Intent.prepareToLeaveProcess(Intent.java:9835)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1612)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:4487)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:30)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:146)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:937)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1047)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:959)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:948)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at com.mvc.imagepicker.ImagePicker.pickImage(ImagePicker.java:106)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at de.baumann.pdfcreator.fragments.add_image.onPickImage(add_image.java:326)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at de.baumann.pdfcreator.fragments.add_image.access$500(add_image.java:46)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at de.baumann.pdfcreator.fragments.add_image$2.onClick(add_image.java:110)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.view.View.performClick(View.java:6294)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:24774)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6499)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-08 14:45:20.603  9106  9106 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-08 14:45:20.605  2210 14552 W ActivityManager:   Force finishing activity de.baumann.pdfcreator/.Activity_Main
06-08 14:45:20.613  2210  2238 I ActivityManager: Showing crash dialog for package de.baumann.pdfcreator u0
`

**Comment by bensonkb** [comment]
Same issue in 8.1 oreo.

**Comment by bege10** [comment]
Same here
Samsung Galaxy S5 Plus (SM-G901F), LineageOS for microG 15.1 (Android 8.1)
